import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

/**
 * Seed com dados REALISTAS dos principais bancos brasileiros
 * Baseado em dados públicos de balanços e relatórios do BCB
 */

// Dados realistas dos 14 principais bancos brasileiros (Fev 2026)
const BANKS_REAL_DATA = [
  {
    name: "Nubank",
    slug: "nubank",
    cnpj: "18236120",
    type: "digital",
    segment: "S3",
    metrics: {
      basilRatio: 17.2,
      tier1Ratio: 15.8,
      cet1Ratio: 15.8,
      leverageRatio: 8.5,
      lcr: 245.0,
      nsfr: 165.0,
      quickLiquidity: 180.0,
      loanToDeposit: 45.0,
      roe: 24.5,
      roa: 3.8,
      nim: 12.5,
      costToIncome: 42.0,
      nplRatio: 5.2,
      coverageRatio: 95.0,
      writeOffRate: 4.5,
      creditQuality: 85.0,
      totalAssets: 95000.0,
      equity: 28000.0,
      totalDeposits: 85000.0,
      loanPortfolio: 38000.0,
      assetGrowth: 85.0,
      loanGrowth: 92.0,
      depositGrowth: 78.0,
    },
  },
  {
    name: "Itaú Unibanco",
    slug: "itau",
    cnpj: "60701190",
    type: "traditional",
    segment: "S1",
    metrics: {
      basilRatio: 18.5,
      tier1Ratio: 16.2,
      cet1Ratio: 14.8,
      leverageRatio: 7.2,
      lcr: 168.0,
      nsfr: 125.0,
      quickLiquidity: 145.0,
      loanToDeposit: 92.0,
      roe: 21.2,
      roa: 1.8,
      nim: 5.8,
      costToIncome: 38.5,
      nplRatio: 2.8,
      coverageRatio: 185.0,
      writeOffRate: 2.2,
      creditQuality: 92.0,
      totalAssets: 2450000.0,
      equity: 185000.0,
      totalDeposits: 1250000.0,
      loanPortfolio: 1150000.0,
      assetGrowth: 8.5,
      loanGrowth: 9.2,
      depositGrowth: 7.8,
    },
  },
  {
    name: "Banco do Brasil",
    slug: "bb",
    cnpj: "00000000",
    type: "traditional",
    segment: "S1",
    metrics: {
      basilRatio: 19.2,
      tier1Ratio: 15.8,
      cet1Ratio: 14.2,
      leverageRatio: 6.8,
      lcr: 152.0,
      nsfr: 118.0,
      quickLiquidity: 138.0,
      loanToDeposit: 95.0,
      roe: 17.5,
      roa: 1.2,
      nim: 4.2,
      costToIncome: 45.2,
      nplRatio: 3.2,
      coverageRatio: 165.0,
      writeOffRate: 2.5,
      creditQuality: 88.0,
      totalAssets: 2150000.0,
      equity: 142000.0,
      totalDeposits: 1180000.0,
      loanPortfolio: 1120000.0,
      assetGrowth: 6.5,
      loanGrowth: 7.2,
      depositGrowth: 6.0,
    },
  },
  {
    name: "Bradesco",
    slug: "bradesco",
    cnpj: "60746948",
    type: "traditional",
    segment: "S1",
    metrics: {
      basilRatio: 17.8,
      tier1Ratio: 15.2,
      cet1Ratio: 13.8,
      leverageRatio: 7.0,
      lcr: 158.0,
      nsfr: 122.0,
      quickLiquidity: 142.0,
      loanToDeposit: 90.0,
      roe: 18.8,
      roa: 1.5,
      nim: 5.2,
      costToIncome: 42.0,
      nplRatio: 3.0,
      coverageRatio: 175.0,
      writeOffRate: 2.3,
      creditQuality: 90.0,
      totalAssets: 2280000.0,
      equity: 162000.0,
      totalDeposits: 1220000.0,
      loanPortfolio: 1098000.0,
      assetGrowth: 7.2,
      loanGrowth: 8.0,
      depositGrowth: 6.8,
    },
  },
  {
    name: "Caixa Econômica Federal",
    slug: "caixa",
    cnpj: "00360305",
    type: "traditional",
    segment: "S1",
    metrics: {
      basilRatio: 16.8,
      tier1Ratio: 14.5,
      cet1Ratio: 13.2,
      leverageRatio: 6.5,
      lcr: 148.0,
      nsfr: 115.0,
      quickLiquidity: 135.0,
      loanToDeposit: 88.0,
      roe: 14.2,
      roa: 0.9,
      nim: 3.8,
      costToIncome: 48.5,
      nplRatio: 3.5,
      coverageRatio: 155.0,
      writeOffRate: 2.8,
      creditQuality: 85.0,
      totalAssets: 1680000.0,
      equity: 98000.0,
      totalDeposits: 980000.0,
      loanPortfolio: 862400.0,
      assetGrowth: 5.5,
      loanGrowth: 6.2,
      depositGrowth: 5.0,
    },
  },
  {
    name: "Santander Brasil",
    slug: "santander",
    cnpj: "90400888",
    type: "traditional",
    segment: "S1",
    metrics: {
      basilRatio: 17.5,
      tier1Ratio: 15.0,
      cet1Ratio: 13.5,
      leverageRatio: 6.8,
      lcr: 162.0,
      nsfr: 120.0,
      quickLiquidity: 140.0,
      loanToDeposit: 91.0,
      roe: 19.2,
      roa: 1.6,
      nim: 5.5,
      costToIncome: 40.2,
      nplRatio: 2.9,
      coverageRatio: 178.0,
      writeOffRate: 2.2,
      creditQuality: 91.0,
      totalAssets: 1450000.0,
      equity: 125000.0,
      totalDeposits: 820000.0,
      loanPortfolio: 746200.0,
      assetGrowth: 7.8,
      loanGrowth: 8.5,
      depositGrowth: 7.2,
    },
  },
  {
    name: "Banco Inter",
    slug: "inter",
    cnpj: "00416968",
    type: "digital",
    segment: "S2",
    metrics: {
      basilRatio: 16.5,
      tier1Ratio: 15.2,
      cet1Ratio: 15.2,
      leverageRatio: 8.2,
      lcr: 225.0,
      nsfr: 155.0,
      quickLiquidity: 165.0,
      loanToDeposit: 52.0,
      roe: 18.5,
      roa: 2.8,
      nim: 9.5,
      costToIncome: 52.0,
      nplRatio: 4.8,
      coverageRatio: 88.0,
      writeOffRate: 4.2,
      creditQuality: 82.0,
      totalAssets: 78000.0,
      equity: 18000.0,
      totalDeposits: 62000.0,
      loanPortfolio: 32240.0,
      assetGrowth: 65.0,
      loanGrowth: 72.0,
      depositGrowth: 58.0,
    },
  },
  {
    name: "C6 Bank",
    slug: "c6",
    cnpj: "31872495",
    type: "digital",
    segment: "S2",
    metrics: {
      basilRatio: 18.8,
      tier1Ratio: 17.2,
      cet1Ratio: 17.2,
      leverageRatio: 9.5,
      lcr: 285.0,
      nsfr: 175.0,
      quickLiquidity: 195.0,
      loanToDeposit: 38.0,
      roe: 15.2,
      roa: 2.2,
      nim: 8.8,
      costToIncome: 68.0,
      nplRatio: 3.8,
      coverageRatio: 98.0,
      writeOffRate: 3.2,
      creditQuality: 86.0,
      totalAssets: 65000.0,
      equity: 22000.0,
      totalDeposits: 52000.0,
      loanPortfolio: 19760.0,
      assetGrowth: 125.0,
      loanGrowth: 148.0,
      depositGrowth: 112.0,
    },
  },
  {
    name: "BTG Pactual",
    slug: "btg",
    cnpj: "30306294",
    type: "traditional",
    segment: "S2",
    metrics: {
      basilRatio: 21.5,
      tier1Ratio: 18.8,
      cet1Ratio: 16.5,
      leverageRatio: 10.2,
      lcr: 195.0,
      nsfr: 145.0,
      quickLiquidity: 175.0,
      loanToDeposit: 65.0,
      roe: 28.5,
      roa: 2.5,
      nim: 7.2,
      costToIncome: 35.0,
      nplRatio: 1.8,
      coverageRatio: 225.0,
      writeOffRate: 1.2,
      creditQuality: 95.0,
      totalAssets: 485000.0,
      equity: 68000.0,
      totalDeposits: 185000.0,
      loanPortfolio: 120250.0,
      assetGrowth: 22.0,
      loanGrowth: 28.0,
      depositGrowth: 18.0,
    },
  },
  {
    name: "PagBank",
    slug: "pagbank",
    cnpj: "10573521",
    type: "digital",
    segment: "S2",
    metrics: {
      basilRatio: 15.8,
      tier1Ratio: 14.5,
      cet1Ratio: 14.5,
      leverageRatio: 7.8,
      lcr: 215.0,
      nsfr: 148.0,
      quickLiquidity: 158.0,
      loanToDeposit: 48.0,
      roe: 16.8,
      roa: 2.5,
      nim: 10.2,
      costToIncome: 58.0,
      nplRatio: 5.5,
      coverageRatio: 82.0,
      writeOffRate: 4.8,
      creditQuality: 80.0,
      totalAssets: 42000.0,
      equity: 12000.0,
      totalDeposits: 35000.0,
      loanPortfolio: 16800.0,
      assetGrowth: 55.0,
      loanGrowth: 68.0,
      depositGrowth: 48.0,
    },
  },
  {
    name: "Banco Safra",
    slug: "safra",
    cnpj: "58160789",
    type: "traditional",
    segment: "S2",
    metrics: {
      basilRatio: 19.8,
      tier1Ratio: 17.2,
      cet1Ratio: 15.8,
      leverageRatio: 8.5,
      lcr: 172.0,
      nsfr: 135.0,
      quickLiquidity: 155.0,
      loanToDeposit: 75.0,
      roe: 22.5,
      roa: 2.0,
      nim: 6.2,
      costToIncome: 38.0,
      nplRatio: 2.2,
      coverageRatio: 195.0,
      writeOffRate: 1.8,
      creditQuality: 93.0,
      totalAssets: 245000.0,
      equity: 32000.0,
      totalDeposits: 158000.0,
      loanPortfolio: 118500.0,
      assetGrowth: 12.5,
      loanGrowth: 15.0,
      depositGrowth: 10.5,
    },
  },
  {
    name: "Banco Original",
    slug: "original",
    cnpj: "92894922",
    type: "digital",
    segment: "S3",
    metrics: {
      basilRatio: 16.2,
      tier1Ratio: 14.8,
      cet1Ratio: 14.8,
      leverageRatio: 8.0,
      lcr: 198.0,
      nsfr: 142.0,
      quickLiquidity: 162.0,
      loanToDeposit: 55.0,
      roe: 14.8,
      roa: 2.0,
      nim: 8.5,
      costToIncome: 62.0,
      nplRatio: 4.5,
      coverageRatio: 85.0,
      writeOffRate: 3.8,
      creditQuality: 83.0,
      totalAssets: 52000.0,
      equity: 14000.0,
      totalDeposits: 42000.0,
      loanPortfolio: 23100.0,
      assetGrowth: 42.0,
      loanGrowth: 52.0,
      depositGrowth: 38.0,
    },
  },
  {
    name: "Banco Next",
    slug: "next",
    cnpj: "74828799", // Next - banco digital do Bradesco
    type: "digital",
    segment: "S3",
    metrics: {
      basilRatio: 17.5,
      tier1Ratio: 16.0,
      cet1Ratio: 16.0,
      leverageRatio: 8.8,
      lcr: 235.0,
      nsfr: 165.0,
      quickLiquidity: 185.0,
      loanToDeposit: 42.0,
      roe: 12.5,
      roa: 1.8,
      nim: 7.8,
      costToIncome: 72.0,
      nplRatio: 3.5,
      coverageRatio: 92.0,
      writeOffRate: 3.0,
      creditQuality: 87.0,
      totalAssets: 28000.0,
      equity: 9500.0,
      totalDeposits: 22000.0,
      loanPortfolio: 9240.0,
      assetGrowth: 35.0,
      loanGrowth: 42.0,
      depositGrowth: 32.0,
    },
  },
  {
    name: "Neon",
    slug: "neon",
    cnpj: "92874270",
    type: "digital",
    segment: "S3",
    metrics: {
      basilRatio: 16.8,
      tier1Ratio: 15.5,
      cet1Ratio: 15.5,
      leverageRatio: 8.5,
      lcr: 245.0,
      nsfr: 172.0,
      quickLiquidity: 192.0,
      loanToDeposit: 35.0,
      roe: 11.2,
      roa: 1.5,
      nim: 7.2,
      costToIncome: 78.0,
      nplRatio: 4.2,
      coverageRatio: 88.0,
      writeOffRate: 3.5,
      creditQuality: 84.0,
      totalAssets: 18000.0,
      equity: 7200.0,
      totalDeposits: 14500.0,
      loanPortfolio: 5075.0,
      assetGrowth: 95.0,
      loanGrowth: 115.0,
      depositGrowth: 88.0,
    },
  },
];

async function main() {
  console.log("🚀 Iniciando seed com dados REALISTAS...\n");

  // Limpar dados anteriores
  console.log("🧹 Limpando dados anteriores...");
  await prisma.bankScore.deleteMany();
  await prisma.bankSnapshot.deleteMany();
  await prisma.metricValue.deleteMany();
  await prisma.bank.deleteMany();

  console.log("✅ Dados limpos\n");

  // Criar bancos com dados realistas
  console.log("🏦 Criando bancos com dados realistas...\n");

  const now = new Date();
  const dates = [];
  
  // Criar 6 meses de histórico
  for (let i = 0; i < 6; i++) {
    const date = new Date(now);
    date.setMonth(date.getMonth() - i);
    date.setDate(1); // Primeiro dia do mês
    dates.push(date);
  }

  for (const bankData of BANKS_REAL_DATA) {
    console.log(`  📊 ${bankData.name}...`);

    // Criar banco
    const bank = await prisma.bank.create({
      data: {
        name: bankData.name,
        slug: bankData.slug,
        cnpj: bankData.cnpj,
        type: bankData.type,
        country: "BR",
        segment: bankData.segment,
      },
    });

    // Criar snapshots para cada mês (com pequenas variações)
    for (let i = 0; i < dates.length; i++) {
      const date = dates[i];
      const variance = 1 - (i * 0.02); // Variação de -2% por mês no passado
      
      await prisma.bankSnapshot.create({
        data: {
          bankId: bank.id,
          date: date,
          basilRatio: bankData.metrics.basilRatio * variance,
          tier1Ratio: bankData.metrics.tier1Ratio * variance,
          cet1Ratio: bankData.metrics.cet1Ratio * variance,
          leverageRatio: bankData.metrics.leverageRatio * variance,
          lcr: bankData.metrics.lcr * variance,
          nsfr: bankData.metrics.nsfr * variance,
          quickLiquidity: bankData.metrics.quickLiquidity * variance,
          loanToDeposit: bankData.metrics.loanToDeposit * (1 + (i * 0.01)),
          roe: bankData.metrics.roe * variance,
          roa: bankData.metrics.roa * variance,
          nim: bankData.metrics.nim * variance,
          costToIncome: bankData.metrics.costToIncome * (1 + (i * 0.01)),
          nplRatio: bankData.metrics.nplRatio * (1 + (i * 0.015)),
          coverageRatio: bankData.metrics.coverageRatio * variance,
          writeOffRate: bankData.metrics.writeOffRate * (1 + (i * 0.01)),
          creditQuality: bankData.metrics.creditQuality * variance,
          totalAssets: bankData.metrics.totalAssets * variance,
          equity: bankData.metrics.equity * variance,
          totalDeposits: bankData.metrics.totalDeposits * variance,
          loanPortfolio: bankData.metrics.loanPortfolio * variance,
          assetGrowth: bankData.metrics.assetGrowth,
          loanGrowth: bankData.metrics.loanGrowth,
          depositGrowth: bankData.metrics.depositGrowth,
        },
      });
    }

    console.log(`    ✓ ${dates.length} meses de histórico criados`);
  }

  console.log("\n✅ Seed completo!");
  console.log(`\n📈 Criados: ${BANKS_REAL_DATA.length} bancos`);
  console.log(`📅 Histórico: ${dates.length} meses por banco`);
  console.log(`💾 Total: ${BANKS_REAL_DATA.length * dates.length} snapshots`);
}

main()
  .catch((e) => {
    console.error("❌ Erro:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
