export const mockBanks = [
  {
    id: "1",
    name: "Nubank",
    slug: "nubank",
    type: "digital",
    country: "BR",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-02-01"),
    score: 85.5,
    lastScoreDate: new Date("2024-02-01"),
  },
  {
    id: "2",
    name: "Itaú Unibanco",
    slug: "itau",
    type: "traditional",
    country: "BR",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-02-01"),
    score: 78.3,
    lastScoreDate: new Date("2024-02-01"),
  },
  {
    id: "3",
    name: "Banco do Brasil",
    slug: "bb",
    type: "traditional",
    country: "BR",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-02-01"),
    score: 72.8,
    lastScoreDate: new Date("2024-02-01"),
  },
  {
    id: "4",
    name: "Bradesco",
    slug: "bradesco",
    type: "traditional",
    country: "BR",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-02-01"),
    score: 75.6,
    lastScoreDate: new Date("2024-02-01"),
  },
  {
    id: "5",
    name: "Caixa Econômica Federal",
    slug: "caixa",
    type: "traditional",
    country: "BR",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-02-01"),
    score: 70.5,
    lastScoreDate: new Date("2024-02-01"),
  },
  {
    id: "6",
    name: "Santander",
    slug: "santander",
    type: "traditional",
    country: "BR",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-02-01"),
    score: 74.2,
    lastScoreDate: new Date("2024-02-01"),
  },
  {
    id: "7",
    name: "Inter",
    slug: "inter",
    type: "digital",
    country: "BR",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-02-01"),
    score: 68.2,
    lastScoreDate: new Date("2024-02-01"),
  },
  {
    id: "8",
    name: "C6 Bank",
    slug: "c6",
    type: "digital",
    country: "BR",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-02-01"),
    score: 81.4,
    lastScoreDate: new Date("2024-02-01"),
  },
  {
    id: "9",
    name: "BTG Pactual",
    slug: "btg",
    type: "traditional",
    country: "BR",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-02-01"),
    score: 88.5,
    lastScoreDate: new Date("2024-02-01"),
  },
  {
    id: "10",
    name: "PagBank",
    slug: "pagbank",
    type: "digital",
    country: "BR",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-02-01"),
    score: 73.8,
    lastScoreDate: new Date("2024-02-01"),
  },
  {
    id: "11",
    name: "Safra",
    slug: "safra",
    type: "traditional",
    country: "BR",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-02-01"),
    score: 83.2,
    lastScoreDate: new Date("2024-02-01"),
  },
  {
    id: "12",
    name: "Original",
    slug: "original",
    type: "digital",
    country: "BR",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-02-01"),
    score: 79.5,
    lastScoreDate: new Date("2024-02-01"),
  },
  {
    id: "13",
    name: "Next",
    slug: "next",
    type: "digital",
    country: "BR",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-02-01"),
    score: 72.2,
    lastScoreDate: new Date("2024-02-01"),
  },
  {
    id: "14",
    name: "Neon",
    slug: "neon",
    type: "digital",
    country: "BR",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-02-01"),
    score: 69.5,
    lastScoreDate: new Date("2024-02-01"),
  },
];

export const mockBankDetails = {
  "1": {
    breakdown: {
      capital: 88.0,
      liquidity: 90.0,
      profitability: 85.0,
      credit: 0,
    },
    metrics: [
      {
        id: "m1",
        date: new Date("2024-02-01"),
        value: 18.5,
        metric: { key: "basel_ratio", label: "Índice de Basileia", unit: "%" },
      },
      {
        id: "m2",
        date: new Date("2024-02-01"),
        value: 22.0,
        metric: { key: "roe", label: "Retorno sobre Patrimônio", unit: "%" },
      },
      {
        id: "m3",
        date: new Date("2024-02-01"),
        value: 145.0,
        metric: { key: "quick_liquidity", label: "Índice de Liquidez Rápida", unit: "%" },
      },
      {
        id: "m4",
        date: new Date("2024-02-01"),
        value: 2.8,
        metric: { key: "npl_ratio", label: "Índice de Inadimplência", unit: "%" },
      },
      {
        id: "m5",
        date: new Date("2024-01-01"),
        value: 18.0,
        metric: { key: "basel_ratio", label: "Índice de Basileia", unit: "%" },
      },
      {
        id: "m6",
        date: new Date("2024-01-01"),
        value: 21.0,
        metric: { key: "roe", label: "Retorno sobre Patrimônio", unit: "%" },
      },
      {
        id: "m7",
        date: new Date("2024-01-01"),
        value: 140.0,
        metric: { key: "quick_liquidity", label: "Índice de Liquidez Rápida", unit: "%" },
      },
      {
        id: "m8",
        date: new Date("2024-01-01"),
        value: 3.1,
        metric: { key: "npl_ratio", label: "Índice de Inadimplência", unit: "%" },
      },
    ],
  },
  "2": {
    breakdown: {
      capital: 75.0,
      liquidity: 82.0,
      profitability: 78.0,
      credit: 0,
    },
    metrics: [
      {
        id: "m9",
        date: new Date("2024-02-01"),
        value: 16.2,
        metric: { key: "basel_ratio", label: "Índice de Basileia", unit: "%" },
      },
      {
        id: "m10",
        date: new Date("2024-02-01"),
        value: 19.5,
        metric: { key: "roe", label: "Retorno sobre Patrimônio", unit: "%" },
      },
      {
        id: "m11",
        date: new Date("2024-02-01"),
        value: 135.0,
        metric: { key: "quick_liquidity", label: "Índice de Liquidez Rápida", unit: "%" },
      },
      {
        id: "m12",
        date: new Date("2024-02-01"),
        value: 3.2,
        metric: { key: "npl_ratio", label: "Índice de Inadimplência", unit: "%" },
      },
    ],
  },
  "3": {
    breakdown: {
      capital: 78.0,
      liquidity: 75.0,
      profitability: 68.0,
      credit: 0,
    },
    metrics: [
      {
        id: "m13",
        date: new Date("2024-02-01"),
        value: 17.8,
        metric: { key: "basel_ratio", label: "Índice de Basileia", unit: "%" },
      },
      {
        id: "m14",
        date: new Date("2024-02-01"),
        value: 18.0,
        metric: { key: "roe", label: "Retorno sobre Patrimônio", unit: "%" },
      },
      {
        id: "m15",
        date: new Date("2024-02-01"),
        value: 140.0,
        metric: { key: "quick_liquidity", label: "Índice de Liquidez Rápida", unit: "%" },
      },
      {
        id: "m16",
        date: new Date("2024-02-01"),
        value: 3.5,
        metric: { key: "npl_ratio", label: "Índice de Inadimplência", unit: "%" },
      },
    ],
  },
  "4": {
    breakdown: {
      capital: 73.0,
      liquidity: 78.0,
      profitability: 76.0,
      credit: 0,
    },
    metrics: [
      {
        id: "m21",
        date: new Date("2024-02-01"),
        value: 16.5,
        metric: { key: "basel_ratio", label: "Índice de Basileia", unit: "%" },
      },
      {
        id: "m22",
        date: new Date("2024-02-01"),
        value: 17.8,
        metric: { key: "roe", label: "Retorno sobre Patrimônio", unit: "%" },
      },
      {
        id: "m23",
        date: new Date("2024-02-01"),
        value: 138.0,
        metric: { key: "quick_liquidity", label: "Índice de Liquidez Rápida", unit: "%" },
      },
      {
        id: "m24",
        date: new Date("2024-02-01"),
        value: 3.4,
        metric: { key: "npl_ratio", label: "Índice de Inadimplência", unit: "%" },
      },
    ],
  },
  "5": {
    breakdown: {
      capital: 70.0,
      liquidity: 72.0,
      profitability: 69.0,
      credit: 0,
    },
    metrics: [
      {
        id: "m29",
        date: new Date("2024-02-01"),
        value: 16.0,
        metric: { key: "basel_ratio", label: "Índice de Basileia", unit: "%" },
      },
      {
        id: "m30",
        date: new Date("2024-02-01"),
        value: 16.5,
        metric: { key: "roe", label: "Retorno sobre Patrimônio", unit: "%" },
      },
      {
        id: "m31",
        date: new Date("2024-02-01"),
        value: 128.0,
        metric: { key: "quick_liquidity", label: "Índice de Liquidez Rápida", unit: "%" },
      },
      {
        id: "m32",
        date: new Date("2024-02-01"),
        value: 3.8,
        metric: { key: "npl_ratio", label: "Índice de Inadimplência", unit: "%" },
      },
    ],
  },
  "6": {
    breakdown: {
      capital: 74.0,
      liquidity: 76.0,
      profitability: 73.0,
      credit: 0,
    },
    metrics: [
      {
        id: "m33",
        date: new Date("2024-02-01"),
        value: 16.8,
        metric: { key: "basel_ratio", label: "Índice de Basileia", unit: "%" },
      },
      {
        id: "m34",
        date: new Date("2024-02-01"),
        value: 18.2,
        metric: { key: "roe", label: "Retorno sobre Patrimônio", unit: "%" },
      },
      {
        id: "m35",
        date: new Date("2024-02-01"),
        value: 133.0,
        metric: { key: "quick_liquidity", label: "Índice de Liquidez Rápida", unit: "%" },
      },
      {
        id: "m36",
        date: new Date("2024-02-01"),
        value: 3.3,
        metric: { key: "npl_ratio", label: "Índice de Inadimplência", unit: "%" },
      },
    ],
  },
  "7": {
    breakdown: {
      capital: 65.0,
      liquidity: 68.0,
      profitability: 72.0,
      credit: 0,
    },
    metrics: [
      {
        id: "m17",
        date: new Date("2024-02-01"),
        value: 15.5,
        metric: { key: "basel_ratio", label: "Índice de Basileia", unit: "%" },
      },
      {
        id: "m18",
        date: new Date("2024-02-01"),
        value: 15.5,
        metric: { key: "roe", label: "Retorno sobre Patrimônio", unit: "%" },
      },
      {
        id: "m19",
        date: new Date("2024-02-01"),
        value: 125.0,
        metric: { key: "quick_liquidity", label: "Índice de Liquidez Rápida", unit: "%" },
      },
      {
        id: "m20",
        date: new Date("2024-02-01"),
        value: 4.0,
        metric: { key: "npl_ratio", label: "Índice de Inadimplência", unit: "%" },
      },
    ],
  },
  "8": {
    breakdown: {
      capital: 82.0,
      liquidity: 80.0,
      profitability: 83.0,
      credit: 0,
    },
    metrics: [
      {
        id: "m25",
        date: new Date("2024-02-01"),
        value: 17.0,
        metric: { key: "basel_ratio", label: "Índice de Basileia", unit: "%" },
      },
      {
        id: "m26",
        date: new Date("2024-02-01"),
        value: 20.0,
        metric: { key: "roe", label: "Retorno sobre Patrimônio", unit: "%" },
      },
      {
        id: "m27",
        date: new Date("2024-02-01"),
        value: 130.0,
        metric: { key: "quick_liquidity", label: "Índice de Liquidez Rápida", unit: "%" },
      },
      {
        id: "m28",
        date: new Date("2024-02-01"),
        value: 3.0,
        metric: { key: "npl_ratio", label: "Índice de Inadimplência", unit: "%" },
      },
    ],
  },
  "9": {
    breakdown: {
      capital: 90.0,
      liquidity: 88.0,
      profitability: 87.0,
      credit: 0,
    },
    metrics: [
      {
        id: "m37",
        date: new Date("2024-02-01"),
        value: 19.5,
        metric: { key: "basel_ratio", label: "Índice de Basileia", unit: "%" },
      },
      {
        id: "m38",
        date: new Date("2024-02-01"),
        value: 24.0,
        metric: { key: "roe", label: "Retorno sobre Patrimônio", unit: "%" },
      },
      {
        id: "m39",
        date: new Date("2024-02-01"),
        value: 155.0,
        metric: { key: "quick_liquidity", label: "Índice de Liquidez Rápida", unit: "%" },
      },
      {
        id: "m40",
        date: new Date("2024-02-01"),
        value: 2.2,
        metric: { key: "npl_ratio", label: "Índice de Inadimplência", unit: "%" },
      },
    ],
  },
  "10": {
    breakdown: {
      capital: 72.0,
      liquidity: 74.0,
      profitability: 75.0,
      credit: 0,
    },
    metrics: [
      {
        id: "m41",
        date: new Date("2024-02-01"),
        value: 16.2,
        metric: { key: "basel_ratio", label: "Índice de Basileia", unit: "%" },
      },
      {
        id: "m42",
        date: new Date("2024-02-01"),
        value: 18.5,
        metric: { key: "roe", label: "Retorno sobre Patrimônio", unit: "%" },
      },
      {
        id: "m43",
        date: new Date("2024-02-01"),
        value: 132.0,
        metric: { key: "quick_liquidity", label: "Índice de Liquidez Rápida", unit: "%" },
      },
      {
        id: "m44",
        date: new Date("2024-02-01"),
        value: 3.1,
        metric: { key: "npl_ratio", label: "Índice de Inadimplência", unit: "%" },
      },
    ],
  },
  "11": {
    breakdown: {
      capital: 84.0,
      liquidity: 83.0,
      profitability: 82.0,
      credit: 0,
    },
    metrics: [
      {
        id: "m45",
        date: new Date("2024-02-01"),
        value: 18.0,
        metric: { key: "basel_ratio", label: "Índice de Basileia", unit: "%" },
      },
      {
        id: "m46",
        date: new Date("2024-02-01"),
        value: 21.5,
        metric: { key: "roe", label: "Retorno sobre Patrimônio", unit: "%" },
      },
      {
        id: "m47",
        date: new Date("2024-02-01"),
        value: 148.0,
        metric: { key: "quick_liquidity", label: "Índice de Liquidez Rápida", unit: "%" },
      },
      {
        id: "m48",
        date: new Date("2024-02-01"),
        value: 2.6,
        metric: { key: "npl_ratio", label: "Índice de Inadimplência", unit: "%" },
      },
    ],
  },
  "12": {
    breakdown: {
      capital: 78.0,
      liquidity: 80.0,
      profitability: 81.0,
      credit: 0,
    },
    metrics: [
      {
        id: "m49",
        date: new Date("2024-02-01"),
        value: 17.2,
        metric: { key: "basel_ratio", label: "Índice de Basileia", unit: "%" },
      },
      {
        id: "m50",
        date: new Date("2024-02-01"),
        value: 19.8,
        metric: { key: "roe", label: "Retorno sobre Patrimônio", unit: "%" },
      },
      {
        id: "m51",
        date: new Date("2024-02-01"),
        value: 142.0,
        metric: { key: "quick_liquidity", label: "Índice de Liquidez Rápida", unit: "%" },
      },
      {
        id: "m52",
        date: new Date("2024-02-01"),
        value: 2.9,
        metric: { key: "npl_ratio", label: "Índice de Inadimplência", unit: "%" },
      },
    ],
  },
  "13": {
    breakdown: {
      capital: 70.0,
      liquidity: 73.0,
      profitability: 74.0,
      credit: 0,
    },
    metrics: [
      {
        id: "m53",
        date: new Date("2024-02-01"),
        value: 15.8,
        metric: { key: "basel_ratio", label: "Índice de Basileia", unit: "%" },
      },
      {
        id: "m54",
        date: new Date("2024-02-01"),
        value: 17.2,
        metric: { key: "roe", label: "Retorno sobre Patrimônio", unit: "%" },
      },
      {
        id: "m55",
        date: new Date("2024-02-01"),
        value: 129.0,
        metric: { key: "quick_liquidity", label: "Índice de Liquidez Rápida", unit: "%" },
      },
      {
        id: "m56",
        date: new Date("2024-02-01"),
        value: 3.6,
        metric: { key: "npl_ratio", label: "Índice de Inadimplência", unit: "%" },
      },
    ],
  },
  "14": {
    breakdown: {
      capital: 68.0,
      liquidity: 70.0,
      profitability: 71.0,
      credit: 0,
    },
    metrics: [
      {
        id: "m57",
        date: new Date("2024-02-01"),
        value: 15.2,
        metric: { key: "basel_ratio", label: "Índice de Basileia", unit: "%" },
      },
      {
        id: "m58",
        date: new Date("2024-02-01"),
        value: 16.8,
        metric: { key: "roe", label: "Retorno sobre Patrimônio", unit: "%" },
      },
      {
        id: "m59",
        date: new Date("2024-02-01"),
        value: 124.0,
        metric: { key: "quick_liquidity", label: "Índice de Liquidez Rápida", unit: "%" },
      },
      {
        id: "m60",
        date: new Date("2024-02-01"),
        value: 4.2,
        metric: { key: "npl_ratio", label: "Índice de Inadimplência", unit: "%" },
      },
    ],
  },
};
