export const mockBanks = [
  {
    id: "1",
    name: "Nubank",
    slug: "nubank",
    type: "digital",
    country: "BR",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-02-01"),
    score: 85.5,
    lastScoreDate: new Date("2024-02-01"),
  },
  {
    id: "2",
    name: "Itaú Unibanco",
    slug: "itau",
    type: "traditional",
    country: "BR",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-02-01"),
    score: 78.3,
    lastScoreDate: new Date("2024-02-01"),
  },
  {
    id: "3",
    name: "Banco do Brasil",
    slug: "bb",
    type: "traditional",
    country: "BR",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-02-01"),
    score: 72.8,
    lastScoreDate: new Date("2024-02-01"),
  },
  {
    id: "4",
    name: "Inter",
    slug: "inter",
    type: "digital",
    country: "BR",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-02-01"),
    score: 68.2,
    lastScoreDate: new Date("2024-02-01"),
  },
  {
    id: "5",
    name: "Bradesco",
    slug: "bradesco",
    type: "traditional",
    country: "BR",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-02-01"),
    score: 75.6,
    lastScoreDate: new Date("2024-02-01"),
  },
  {
    id: "6",
    name: "C6 Bank",
    slug: "c6",
    type: "digital",
    country: "BR",
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-02-01"),
    score: 81.4,
    lastScoreDate: new Date("2024-02-01"),
  },
];

export const mockBankDetails = {
  "1": {
    breakdown: {
      capital: 88.0,
      liquidity: 90.0,
      profitability: 85.0,
      credit: 0,
    },
    metrics: [
      {
        id: "m1",
        date: new Date("2024-02-01"),
        value: 18.5,
        metric: { key: "basel_ratio", label: "Índice de Basileia", unit: "%" },
      },
      {
        id: "m2",
        date: new Date("2024-02-01"),
        value: 22.0,
        metric: { key: "roe", label: "Retorno sobre Patrimônio", unit: "%" },
      },
      {
        id: "m3",
        date: new Date("2024-02-01"),
        value: 145.0,
        metric: { key: "quick_liquidity", label: "Índice de Liquidez Rápida", unit: "%" },
      },
      {
        id: "m4",
        date: new Date("2024-02-01"),
        value: 2.8,
        metric: { key: "npl_ratio", label: "Índice de Inadimplência", unit: "%" },
      },
      {
        id: "m5",
        date: new Date("2024-01-01"),
        value: 18.0,
        metric: { key: "basel_ratio", label: "Índice de Basileia", unit: "%" },
      },
      {
        id: "m6",
        date: new Date("2024-01-01"),
        value: 21.0,
        metric: { key: "roe", label: "Retorno sobre Patrimônio", unit: "%" },
      },
      {
        id: "m7",
        date: new Date("2024-01-01"),
        value: 140.0,
        metric: { key: "quick_liquidity", label: "Índice de Liquidez Rápida", unit: "%" },
      },
      {
        id: "m8",
        date: new Date("2024-01-01"),
        value: 3.1,
        metric: { key: "npl_ratio", label: "Índice de Inadimplência", unit: "%" },
      },
    ],
  },
  "2": {
    breakdown: {
      capital: 75.0,
      liquidity: 82.0,
      profitability: 78.0,
      credit: 0,
    },
    metrics: [
      {
        id: "m9",
        date: new Date("2024-02-01"),
        value: 16.2,
        metric: { key: "basel_ratio", label: "Índice de Basileia", unit: "%" },
      },
      {
        id: "m10",
        date: new Date("2024-02-01"),
        value: 19.5,
        metric: { key: "roe", label: "Retorno sobre Patrimônio", unit: "%" },
      },
      {
        id: "m11",
        date: new Date("2024-02-01"),
        value: 135.0,
        metric: { key: "quick_liquidity", label: "Índice de Liquidez Rápida", unit: "%" },
      },
      {
        id: "m12",
        date: new Date("2024-02-01"),
        value: 3.2,
        metric: { key: "npl_ratio", label: "Índice de Inadimplência", unit: "%" },
      },
    ],
  },
  "3": {
    breakdown: {
      capital: 78.0,
      liquidity: 75.0,
      profitability: 68.0,
      credit: 0,
    },
    metrics: [
      {
        id: "m13",
        date: new Date("2024-02-01"),
        value: 17.8,
        metric: { key: "basel_ratio", label: "Índice de Basileia", unit: "%" },
      },
      {
        id: "m14",
        date: new Date("2024-02-01"),
        value: 18.0,
        metric: { key: "roe", label: "Retorno sobre Patrimônio", unit: "%" },
      },
      {
        id: "m15",
        date: new Date("2024-02-01"),
        value: 140.0,
        metric: { key: "quick_liquidity", label: "Índice de Liquidez Rápida", unit: "%" },
      },
      {
        id: "m16",
        date: new Date("2024-02-01"),
        value: 3.5,
        metric: { key: "npl_ratio", label: "Índice de Inadimplência", unit: "%" },
      },
    ],
  },
  "4": {
    breakdown: {
      capital: 65.0,
      liquidity: 68.0,
      profitability: 72.0,
      credit: 0,
    },
    metrics: [
      {
        id: "m17",
        date: new Date("2024-02-01"),
        value: 15.5,
        metric: { key: "basel_ratio", label: "Índice de Basileia", unit: "%" },
      },
      {
        id: "m18",
        date: new Date("2024-02-01"),
        value: 15.5,
        metric: { key: "roe", label: "Retorno sobre Patrimônio", unit: "%" },
      },
      {
        id: "m19",
        date: new Date("2024-02-01"),
        value: 125.0,
        metric: { key: "quick_liquidity", label: "Índice de Liquidez Rápida", unit: "%" },
      },
      {
        id: "m20",
        date: new Date("2024-02-01"),
        value: 4.0,
        metric: { key: "npl_ratio", label: "Índice de Inadimplência", unit: "%" },
      },
    ],
  },
  "5": {
    breakdown: {
      capital: 73.0,
      liquidity: 78.0,
      profitability: 76.0,
      credit: 0,
    },
    metrics: [
      {
        id: "m21",
        date: new Date("2024-02-01"),
        value: 16.5,
        metric: { key: "basel_ratio", label: "Índice de Basileia", unit: "%" },
      },
      {
        id: "m22",
        date: new Date("2024-02-01"),
        value: 17.8,
        metric: { key: "roe", label: "Retorno sobre Patrimônio", unit: "%" },
      },
      {
        id: "m23",
        date: new Date("2024-02-01"),
        value: 138.0,
        metric: { key: "quick_liquidity", label: "Índice de Liquidez Rápida", unit: "%" },
      },
      {
        id: "m24",
        date: new Date("2024-02-01"),
        value: 3.4,
        metric: { key: "npl_ratio", label: "Índice de Inadimplência", unit: "%" },
      },
    ],
  },
  "6": {
    breakdown: {
      capital: 82.0,
      liquidity: 80.0,
      profitability: 83.0,
      credit: 0,
    },
    metrics: [
      {
        id: "m25",
        date: new Date("2024-02-01"),
        value: 17.0,
        metric: { key: "basel_ratio", label: "Índice de Basileia", unit: "%" },
      },
      {
        id: "m26",
        date: new Date("2024-02-01"),
        value: 20.0,
        metric: { key: "roe", label: "Retorno sobre Patrimônio", unit: "%" },
      },
      {
        id: "m27",
        date: new Date("2024-02-01"),
        value: 130.0,
        metric: { key: "quick_liquidity", label: "Índice de Liquidez Rápida", unit: "%" },
      },
      {
        id: "m28",
        date: new Date("2024-02-01"),
        value: 3.0,
        metric: { key: "npl_ratio", label: "Índice de Inadimplência", unit: "%" },
      },
    ],
  },
};
